#!/bin/bash
find papers -type f -name "*.tex" -exec sed -i 's/\\documentclass{.*}//g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/\\usepackage{.*}//g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/\\title{.*}//g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/\\author{.*}//g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/\\date{.*}//g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/\\maketitle//g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/\\begin{document}//g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/\\end{document}//g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/\\begin{abstract}//g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/\\end{abstract}//g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/\\newtheorem{.*}//g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/\\newunicodechar{.*}{.*}//g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/\\setlength{.*}{.*}//g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/’/\\textquotesingle /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/–/\\textendash /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/“/\\textquotedblleft /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/”/\\textquotedblright /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/→/$\\to$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/↛/$\\nrightarrow$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/↔/$\\leftrightarrow$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/⊢/$\\vdash$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/⊨/$\\models$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/⊥/$\\bot$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/⊤/$\\top$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/¬/$\\neg$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/∨/$\\lor$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/∧/$\\land$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/⊕/$\\oplus$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/⊗/$\\otimes$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/⅋/$\\parr$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/↓/$\\downarrow$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/↑/$\\uparrow$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/∀/$\\forall$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/∃/$\\exists$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/Γ/$\\Gamma$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/Δ/$\\Delta$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/θ/$\\theta$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/λ/$\\lambda$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/σ/$\\sigma$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/Σ/$\\Sigma$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/ω/$\\omega$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/ψ/$\\psi$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/Ψ/$\\Psi$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/Φ/$\\Phi$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/π/$\\pi$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/ε/$\\epsilon$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/Π/$\\Pi$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/α/$\\alpha$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/β/$\\beta$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/γ/$\\gamma$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/δ/$\\delta$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/ζ/$\\zeta$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/η/$\\eta$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/ι/$\\iota$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/κ/$\\kappa$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/μ/$\\mu$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/ν/$\\nu$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/ξ/$\\xi$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/ρ/$\\rho$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/τ/$\\tau$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/υ/$\\upsilon$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/φ/$\\phi$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/χ/$\\chi$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/⊬/$\\nmodels$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/□/$\\square$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/◇/$\\diamond$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/𝕽/$\\mathbb{R}$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/…/\\dots /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/′/\\textquotesingle /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/↚/$\\nleftarrow$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/≔/$\\coloneqq$ /g' {} \;
find papers -type f -name "*.tex" -exec sed -i 's/≠/$\\neq$ /g' {} \;